### ISSUE TITLE
[FEATURE REQUEST] Show all the artists when displaying the top and recent track

### ISSUE THREAD

**Issue by msr8** [ZenithDS/SpotiFetch#1]
![Screenshot 2022-03-20 at 16 39 30](https://user-images.githubusercontent.com/79649185/159159438-730b96a8-5189-4eff-b364-fa99836232ba.png)

For example here, the songs [army](https://open.spotify.com/track/2cGYpPNtn60ceiB7ddfEpw) and [kult](https://open.spotify.com/track/22ya9ZSp7FxhcgFLALm0eS) have multiple artists. I think it would look cooler if spotifetch showed all the artists, such as
```
RECENT TRACK    ARMY - BESOMORPH, ARCANDO, NEONI
TOP TRACK       KULT (FEAT. JASIAH) - STEVE AOKI, GRANDSON, JASIAH
```

**Comment by ZenithDS** [comment]
Thank you for the feedback! Displaying only one artist was a deliberate design choice I made in order to reduce clutter since some songs could possibly have tons of artists. With that said, I can certainly add this as an optional flag for those who want to use it. Would you like to see the same for the `spotifetch top-tracks` or just `spotifetch profile` ?

**Comment by ZenithDS** [comment]
After just a little bit of work, this feature has been added in aa088f3. I've also updated the documentation to show usage of this feature. Please let me know what you think :)

**Comment by msr8** [comment]
Yupp, works exactly as I wanted! And I don't see myself using `top-tracks` or `profile` args anytime soon, but maybe other users would like seeing multiple artists in those
